<h1> Nifty100_ML_enhancement phase</h1>
<h2> shortout and Handle some problem, mistakes and errors</h2>

In [4]:
import pandas as pd
import numpy as np
ml_df = pd.read_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\company_health_scores.csv"
)

ml_df.head()

,symbol,company_name,fiscal_year,net_profit_margin_pct,expense_ratio_pct,debt_to_equity,free_cash_flow,net_profit,profitability_score,expense_score,debt_score,cashflow_score,health_score,health_category
0,ABB,Abbott India Ltd,2024,20.533425,75.158147,0.022438,797.0,1201,25,18,25,25,93,STRONG
1,ADANIENSOL,Adani Energy Solutions Ltd,2024,7.201782,65.610887,2.932521,1095.0,1196,10,18,8,25,61,WEAK
2,ADANIENT,Adani Enterprises Ltd,2024,3.458790,88.200703,1.671358,-8455.0,3335,10,10,18,10,48,WEAK
3,ADANIGREEN,Adani Green Energy Ltd,2024,13.665944,20.629067,6.595282,-13347.0,1260,18,25,8,10,61,WEAK
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd,2024,30.339560,41.634533,0.937322,8250.0,8104,25,25,25,25,100,STRONG

In [5]:
ml_df.columns

Index(['symbol', 'company_name', 'fiscal_year', 'net_profit_margin_pct',
       'expense_ratio_pct', 'debt_to_equity', 'free_cash_flow', 'net_profit',
       'profitability_score', 'expense_score', 'debt_score', 'cashflow_score',
       'health_score', 'health_category'],
      dtype='str')

In [6]:
# Add Missing ML Score Columns
profit = pd.read_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\profit_clean.csv"
)

latest_year = ml_df['fiscal_year'].max()

latest_profit = profit[profit['fiscal_year'] == latest_year][[
    'symbol',
    'dividend_payout'
]].drop_duplicates(subset=['symbol'])

ml_df = ml_df.merge(
    latest_profit,
    on='symbol',
    how='left'
)

ml_df['overall_score'] = ml_df['health_score']

ml_df['leverage_score'] = ml_df['debt_score']

ml_df['dividend_score'] = np.where(
    ml_df['dividend_payout'].fillna(0) >= 30, 20,
    np.where(ml_df['dividend_payout'].fillna(0) >= 10, 12, 6)
)

ml_df['growth_score'] = np.where(
    ml_df['net_profit_margin_pct'] >= 20, 20,
    np.where(ml_df['net_profit_margin_pct'] >= 10, 14, 8)
)

ml_df['trend_score'] = np.where(
    ml_df['free_cash_flow'] > 0, 20, 8
)

ml_df.head()

,symbol,company_name,fiscal_year,net_profit_margin_pct,expense_ratio_pct,debt_to_equity,free_cash_flow,net_profit,profitability_score,expense_score,debt_score,cashflow_score,health_score,health_category,dividend_payout,overall_score,leverage_score,dividend_score,growth_score,trend_score
0,ABB,Abbott India Ltd,2024,20.533425,75.158147,0.022438,797.0,1201,25,18,25,25,93,STRONG,73.0,93,25,20,20,20
1,ADANIENSOL,Adani Energy Solutions Ltd,2024,7.201782,65.610887,2.932521,1095.0,1196,10,18,8,25,61,WEAK,0.0,61,8,6,8,20
2,ADANIENT,Adani Enterprises Ltd,2024,3.458790,88.200703,1.671358,-8455.0,3335,10,10,18,10,48,WEAK,5.0,48,18,6,8,8
3,ADANIGREEN,Adani Green Energy Ltd,2024,13.665944,20.629067,6.595282,-13347.0,1260,18,25,8,10,61,WEAK,0.0,61,8,6,14,8
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd,2024,30.339560,41.634533,0.937322,8250.0,8104,25,25,25,25,100,STRONG,16.0,100,25,12,20,20

In [7]:
ml_df.columns

Index(['symbol', 'company_name', 'fiscal_year', 'net_profit_margin_pct',
       'expense_ratio_pct', 'debt_to_equity', 'free_cash_flow', 'net_profit',
       'profitability_score', 'expense_score', 'debt_score', 'cashflow_score',
       'health_score', 'health_category', 'dividend_payout', 'overall_score',
       'leverage_score', 'dividend_score', 'growth_score', 'trend_score'],
      dtype='str')

In [8]:
# Final Save
ml_df.to_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\company_updated_health_scores.csv",
    index=False
)

print("company_updated_health_scores.csv created successfully.")

company_updated_health_scores.csv created successfully.

In [9]:
# CROSS CHECK
import os

os.listdir(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean"
)

['analysis_clean.csv',
 'balancesheet_clean.csv',
 'cashflow_clean.csv',
 'companies_clean.csv',
 'company_health_scores.csv',
 'company_updated_health_scores.csv',
 'profit_clean.csv',
 'prosandcons.csv',
 'prosandcons_clean.csv']

In [10]:
# Load Updated CSV
ml_updated_df = pd.read_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\company_updated_health_scores.csv"
)

ml_updated_df.head()

,symbol,company_name,fiscal_year,net_profit_margin_pct,expense_ratio_pct,debt_to_equity,free_cash_flow,net_profit,profitability_score,expense_score,debt_score,cashflow_score,health_score,health_category,dividend_payout,overall_score,leverage_score,dividend_score,growth_score,trend_score
0,ABB,Abbott India Ltd,2024,20.533425,75.158147,0.022438,797.0,1201,25,18,25,25,93,STRONG,73.0,93,25,20,20,20
1,ADANIENSOL,Adani Energy Solutions Ltd,2024,7.201782,65.610887,2.932521,1095.0,1196,10,18,8,25,61,WEAK,0.0,61,8,6,8,20
2,ADANIENT,Adani Enterprises Ltd,2024,3.458790,88.200703,1.671358,-8455.0,3335,10,10,18,10,48,WEAK,5.0,48,18,6,8,8
3,ADANIGREEN,Adani Green Energy Ltd,2024,13.665944,20.629067,6.595282,-13347.0,1260,18,25,8,10,61,WEAK,0.0,61,8,6,14,8
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd,2024,30.339560,41.634533,0.937322,8250.0,8104,25,25,25,25,100,STRONG,16.0,100,25,12,20,20

In [11]:
ml_updated_df.columns

Index(['symbol', 'company_name', 'fiscal_year', 'net_profit_margin_pct',
       'expense_ratio_pct', 'debt_to_equity', 'free_cash_flow', 'net_profit',
       'profitability_score', 'expense_score', 'debt_score', 'cashflow_score',
       'health_score', 'health_category', 'dividend_payout', 'overall_score',
       'leverage_score', 'dividend_score', 'growth_score', 'trend_score'],
      dtype='str')

In [12]:
# Create Warehouse Load Version
fact_ml_scores_df = ml_updated_df[[
    'symbol',
    'overall_score',
    'profitability_score',
    'growth_score',
    'leverage_score',
    'cashflow_score',
    'dividend_score',
    'trend_score',
    'health_category'
]].copy()

fact_ml_scores_df = fact_ml_scores_df.rename(columns={
    'health_category': 'health_label'
})

fact_ml_scores_df.head()

,symbol,overall_score,profitability_score,growth_score,leverage_score,cashflow_score,dividend_score,trend_score,health_label
0,ABB,93,25,20,25,25,20,20,STRONG
1,ADANIENSOL,61,10,8,8,25,6,20,WEAK
2,ADANIENT,48,10,8,18,10,6,8,WEAK
3,ADANIGREEN,61,18,14,8,10,6,8,WEAK
4,ADANIPORTS,100,25,20,25,25,12,20,STRONG

In [13]:
# Save Warehouse Fact CSV
fact_ml_scores_df.to_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\fact_ml_scores.csv",
    index=False
)

print("fact_ml_scores.csv created successfully.")

fact_ml_scores.csv created successfully.

In [14]:
# Cross check
fact_ml_scores_df.shape

(98, 9)

<h2> UPDATE Some clean files AND create some NEW clean files </h2>

In [1]:
# load required files and libraries
import pandas as pd
import numpy as np

BASE_DIR = r"C:\Users\LENOVO\Desktop\nifty100_project"

companies_df = pd.read_csv(
    BASE_DIR + r"\data\clean\companies_clean.csv"
)

scores_df = pd.read_csv(
    BASE_DIR + r"\data\clean\company_updated_health_scores.csv"
)

print("companies:", companies_df.shape)
print("scores:", scores_df.shape)

companies_df[['symbol', 'company_name', 'sector', 'sub_sector']].head()

companies: (92, 14)
scores: (98, 20)

       symbol                             company_name  sector  sub_sector
0         ABB                         Abbott India Ltd     NaN         NaN
1  ADANIENSOL               Adani Energy Solutions Ltd     NaN         NaN
2    ADANIENT                    Adani Enterprises Ltd     NaN         NaN
3  ADANIGREEN                   Adani Green Energy Ltd     NaN         NaN
4  ADANIPORTS  Adani Ports & Special Economic Zone Ltd     NaN         NaN

In [2]:
# Check available company symbols
companies_df[['symbol', 'company_name']].sort_values('symbol').to_string()

'        symbol                                                                company_name\n0          ABB                                                            Abbott India Ltd\n1   ADANIENSOL                                                  Adani Energy Solutions Ltd\n2     ADANIENT                                                       Adani Enterprises Ltd\n3   ADANIGREEN                                                      Adani Green Energy Ltd\n4   ADANIPORTS                                     Adani Ports & Special Economic Zone Ltd\n5   ADANIPOWER                                                             Adani Power Ltd\n6    AMBUJACEM                                                          Ambuja Cements Ltd\n7   APOLLOHOSP                          Apollo Hospitals Chain of Indian private hospitals\n8   ASIANPAINT  Asian Paints Indian Multi-National Paint and Coating Manufacturing Company\n9         ATGL                                                         Adani Total Gas Ltd\n10    AXISBANK                                                               Axis Bank Ltd\n11  BAJAJ-AUTO                                                              Bajaj Auto Ltd\n12  BAJAJFINSV                                                           Bajaj Finserv Ltd\n13  BAJAJHLDNG                                             Bajaj Holdings & Investment Ltd\n14  BAJFINANCE                                                           Bajaj Finance Ltd\n15  BANKBARODA                                                              Bank of Baroda\n16         BEL                                                      Bharat Electronics Ltd\n17  BHARTIARTL                                                           Bharti Airtel Ltd\n18        BHEL                                            Bharat Heavy Electricals Limited\n19    BOSCHLTD                                                                   Bosch Ltd\n20        BPCL                                            Bharat Petroleum Corporation Ltd\n21   BRITANNIA                                                    Britannia Industries Ltd\n22       CANBK                                                                 Canara Bank\n23    CHOLAFIN                              Cholamandalam Investment & Finance Company Ltd\n24       CIPLA                                                                   Cipla Ltd\n25   COALINDIA                                                              Coal India Ltd\n26       DABUR                                                             Dabur India Ltd\n27    DIVISLAB                                                      Divis Laboratories Ltd\n28         DLF                                                                     DLF Ltd\n29       DMART                                                       Avenue Supermarts Ltd\n30     DRREDDY                                                  Dr Reddys Laboratories Ltd\n31   EICHERMOT                                                           Eicher Motors Ltd\n32        GAIL                                                            GAIL (India) Ltd\n33    GODREJCP                                                Godrej Consumer Products Ltd\n34      GRASIM                                                       Grasim Industries Ltd\n35         HAL                                                   Hindustan Aeronautics Ltd\n36     HAVELLS                                                           Havells India Ltd\n37     HCLTECH                                                        HCL Technologies Ltd\n38    HDFCBANK                                                               HDFC Bank Ltd\n39    HDFCLIFE                                             HDFC Life Insurance Company Ltd\n40  HEROMOTOCO                                                           Hero MotoCorp Ltd\n41    HINDALCO                                                     Hindalco Industries Ltd\n42  HINDUNILVR                                                      Hindustan Unilever Ltd\n43   ICICIBANK                                                              ICICI Bank Ltd\n44     ICICIGI                                 ICICI Lombard General Insurance Company Ltd\n45  ICICIPRULI                                 ICICI Prudential Life Insurance Company Ltd\n46      INDIGO                                                     Interglobe Aviation Ltd\n47  INDUSINDBK                                                           IndusInd Bank Ltd\n48        INFY                                                                 Infosys Ltd\n49         IOC                                                      Indian Oil Corporation\n50       IRCTC                           Indian Railway Catering & Tourism Corporation Ltd\n51        IRFC                                      Indian Railway Finance Corporation Ltd\n52         ITC                                                                     ITC Ltd\n53  JINDALSTEL                                                    Jindal Steel & Power Ltd\n54      JIOFIN                                                  Jio Financial Services Ltd\n55   JSWENERGY                                                              JSW Energy Ltd\n56    JSWSTEEL                                                               JSW Steel Ltd\n57   KOTAKBANK                                                     Kotak Mahindra Bank Ltd\n58        LICI                                         Life Insurance Corporation of India\n59       LODHA                                                    Macrotech Developers Ltd\n60          LT                                                         Larsen & Toubro Ltd\n61        LTIM                                                             LTIMindtree Ltd\n62         M&M                                                     Mahindra & Mahindra Ltd\n63      MARUTI                                                     Maruti Suzuki India Ltd\n64   MOTHERSON                                     Samvardhana Motherson International Ltd\n65      NAUKRI                                                       Info Edge (India) Ltd\n66   NESTLEIND                                                            Nestle India Ltd\n67        NHPC                                                                    NHPC Ltd\n68        NTPC                                                                    NTPC Ltd\n69        ONGC                                                 Oil & Natural Gas Corpn Ltd\n70         PFC                                               Power Finance Corporation Ltd\n71  PIDILITIND                                                     Pidilite Industries Ltd\n72         PNB                                                        Punjab National Bank\n73   POWERGRID                                         Power Grid Corporation of India Ltd\n74      RECLTD                                                                     REC Ltd\n75    RELIANCE                                                     Reliance Industries Ltd\n76     SBILIFE                                              SBI Life Insurance Company Ltd\n77        SBIN                                                         State Bank of India\n78    SHREECEM                                                            Shree Cement Ltd\n79  SHRIRAMFIN                                                         Shriram Finance Ltd\n80     SIEMENS                                                                 Siemens Ltd\n81   SUNPHARMA                                          Sun Pharmaceuticals Industries Ltd\n82  TATACONSUM                                                  Tata Consumer Products Ltd\n83  TATAMOTORS                                                             Tata Motors Ltd\n84   TATAPOWER                                                      Tata Power Company Ltd\n85   TATASTEEL                                                              Tata Steel Ltd\n86         TCS                                               Tata Consultancy Services Ltd\n87       TECHM                                                           Tech Mahindra Ltd\n88       TITAN                                                           Titan Company Ltd\n89  TORNTPHARM                                                 Torrent Pharmaceuticals Ltd\n90       TRENT                                                                   Trent Ltd\n91    TVSMOTOR                                                       TVS Motor Company Ltd'

In [3]:
# Create Sector Mapping Dictionary
sector_mapping = {
    'ABB': ('PHARMA', 'Healthcare'),
    'ADANIENSOL': ('POWER', 'Power Transmission'),
    'ADANIENT': ('ENERGY', 'Diversified Energy'),
    'ADANIGREEN': ('POWER', 'Renewable Energy'),
    'ADANIPORTS': ('PORTS', 'Ports & Logistics'),
    'ADANIPOWER': ('POWER', 'Power Generation'),
    'AMBUJACEM': ('CEMENT', 'Cement'),
    'APOLLOHOSP': ('HEALTHCARE', 'Hospitals'),
    'ASIANPAINT': ('PAINT', 'Paints'),
    'ATGL': ('ENERGY', 'Gas Distribution'),
    'AXISBANK': ('BANKING', 'Private Bank'),
    'BAJAJ-AUTO': ('AUTO', 'Two Wheelers'),
    'BAJAJFINSV': ('NBFC', 'Financial Services'),
    'BAJAJHLDNG': ('HOLDING COMPANY', 'Investment Holding'),
    'BAJFINANCE': ('NBFC', 'Consumer Finance'),
    'BANKBARODA': ('BANKING', 'Public Bank'),
    'BEL': ('DEFENCE', 'Defence Electronics'),
    'BHARTIARTL': ('TELECOM', 'Telecom Services'),
    'BHEL': ('POWER', 'Heavy Electrical Equipment'),
    'BOSCHLTD': ('AUTO', 'Auto Components'),
    'BPCL': ('ENERGY', 'Oil & Gas'),
    'BRITANNIA': ('FMCG', 'Food Products'),
    'CANBK': ('BANKING', 'Public Bank'),
    'CHOLAFIN': ('NBFC', 'Vehicle Finance'),
    'CIPLA': ('PHARMA', 'Pharmaceuticals'),
    'COALINDIA': ('METALS', 'Mining'),
    'DABUR': ('FMCG', 'Consumer Goods'),
    'DIVISLAB': ('PHARMA', 'Pharmaceuticals'),
    'DLF': ('REAL ESTATE', 'Real Estate'),
    'DMART': ('CONSUMER GOODS', 'Retail'),
    'DRREDDY': ('PHARMA', 'Pharmaceuticals'),
    'EICHERMOT': ('AUTO', 'Automobiles'),
    'GAIL': ('ENERGY', 'Gas Utility'),
    'GODREJCP': ('FMCG', 'Consumer Goods'),
    'GRASIM': ('CEMENT', 'Diversified Cement'),
    'HAL': ('DEFENCE', 'Aerospace & Defence'),
    'HAVELLS': ('CONSUMER GOODS', 'Electrical Products'),
    'HCLTECH': ('IT', 'IT Services'),
    'HDFCBANK': ('BANKING', 'Private Bank'),
    'HDFCLIFE': ('INSURANCE', 'Life Insurance'),
    'HEROMOTOCO': ('AUTO', 'Two Wheelers'),
    'HINDALCO': ('METALS', 'Metals'),
    'HINDUNILVR': ('FMCG', 'Consumer Goods'),
    'ICICIBANK': ('BANKING', 'Private Bank'),
    'ICICIGI': ('INSURANCE', 'General Insurance'),
    'ICICIPRULI': ('INSURANCE', 'Life Insurance'),
    'INDIGO': ('AVIATION', 'Airlines'),
    'INDUSINDBK': ('BANKING', 'Private Bank'),
    'INFY': ('IT', 'IT Services'),
    'IOC': ('ENERGY', 'Oil & Gas'),
    'IRCTC': ('TRANSPORT', 'Railway Services'),
    'IRFC': ('NBFC', 'Railway Finance'),
    'ITC': ('FMCG', 'Consumer Goods'),
    'JINDALSTEL': ('METALS', 'Steel'),
    'JIOFIN': ('NBFC', 'Financial Services'),
    'JSWENERGY': ('POWER', 'Power Generation'),
    'JSWSTEEL': ('METALS', 'Steel'),
    'KOTAKBANK': ('BANKING', 'Private Bank'),
    'LICI': ('INSURANCE', 'Life Insurance'),
    'LODHA': ('REAL ESTATE', 'Real Estate'),
    'LT': ('INFRASTRUCTURE', 'Engineering & Construction'),
    'LTIM': ('IT', 'IT Services'),
    'M&M': ('AUTO', 'Automobiles'),
    'MARUTI': ('AUTO', 'Passenger Vehicles'),
    'MOTHERSON': ('AUTO', 'Auto Components'),
    'NAUKRI': ('IT', 'Internet Services'),
    'NESTLEIND': ('FMCG', 'Food Products'),
    'NHPC': ('POWER', 'Hydro Power'),
    'NTPC': ('POWER', 'Power Generation'),
    'ONGC': ('ENERGY', 'Oil Exploration'),
    'PFC': ('NBFC', 'Power Finance'),
    'PIDILITIND': ('CHEMICALS', 'Adhesives'),
    'PNB': ('BANKING', 'Public Bank'),
    'POWERGRID': ('POWER', 'Power Transmission'),
    'RECLTD': ('NBFC', 'Power Finance'),
    'RELIANCE': ('ENERGY', 'Conglomerate'),
    'SBILIFE': ('INSURANCE', 'Life Insurance'),
    'SBIN': ('BANKING', 'Public Bank'),
    'SHREECEM': ('CEMENT', 'Cement'),
    'SHRIRAMFIN': ('NBFC', 'Retail Finance'),
    'SIEMENS': ('INDUSTRIALS', 'Industrial Equipment'),
    'SUNPHARMA': ('PHARMA', 'Pharmaceuticals'),
    'TATACONSUM': ('FMCG', 'Consumer Goods'),
    'TATAMOTORS': ('AUTO', 'Automobiles'),
    'TATAPOWER': ('POWER', 'Power Generation'),
    'TATASTEEL': ('METALS', 'Steel'),
    'TCS': ('IT', 'IT Services'),
    'TECHM': ('IT', 'IT Services'),
    'TITAN': ('CONSUMER GOODS', 'Jewellery & Lifestyle'),
    'TORNTPHARM': ('PHARMA', 'Pharmaceuticals'),
    'TRENT': ('CONSUMER GOODS', 'Retail'),
    'TVSMOTOR': ('AUTO', 'Two Wheelers')
}

In [4]:
# Convert Sector Mapping to DataFrame
sector_mapping_df = pd.DataFrame(
    [
        {
            "symbol": symbol,
            "sector": values[0],
            "sub_sector": values[1]
        }
        for symbol, values in sector_mapping.items()
    ]
)

sector_mapping_df.head()

       symbol  sector          sub_sector
0         ABB  PHARMA          Healthcare
1  ADANIENSOL   POWER  Power Transmission
2    ADANIENT  ENERGY  Diversified Energy
3  ADANIGREEN   POWER    Renewable Energy
4  ADANIPORTS   PORTS   Ports & Logistics

In [5]:
# Cross Check Mapping Count
print("Sector mapping rows:", sector_mapping_df.shape[0])
print("Companies rows:", companies_df.shape[0])

missing_in_mapping = set(companies_df["symbol"]) - set(sector_mapping_df["symbol"])
extra_in_mapping = set(sector_mapping_df["symbol"]) - set(companies_df["symbol"])

print("Missing in mapping:", missing_in_mapping)
print("Extra in mapping:", extra_in_mapping)

Sector mapping rows: 92
Companies rows: 92
Missing in mapping: set()
Extra in mapping: set()

In [6]:
# Save sector_mapping.csv
sector_mapping_df.to_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\sector_mapping.csv",
    index=False
)

print("sector_mapping.csv saved successfully.")

sector_mapping.csv saved successfully.

In [7]:
# Create updated_companies_clean.csv
updated_companies_df = companies_df.drop(columns=["sector", "sub_sector"], errors="ignore")

updated_companies_df = updated_companies_df.merge(
    sector_mapping_df,
    on="symbol",
    how="left"
)

updated_companies_df.head()

,symbol,company_logo,company_name,chart_link,about_company,website,nse_url,bse_url,face_value,book_value,roce,roe,sector,sub_sector
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90,PHARMA,Healthcare
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59,POWER,Power Transmission
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64,ENERGY,Diversified Energy
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70,POWER,Renewable Energy
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10,PORTS,Ports & Logistics

In [8]:
# Cross Check Updated Companies
print(updated_companies_df[["sector", "sub_sector"]].isnull().sum())

updated_companies_df[["symbol", "company_name", "sector", "sub_sector"]].head(10)

sector        0
sub_sector    0
dtype: int64

,symbol,company_name,sector,sub_sector
0,ABB,Abbott India Ltd,PHARMA,Healthcare
1,ADANIENSOL,Adani Energy Solutions Ltd,POWER,Power Transmission
2,ADANIENT,Adani Enterprises Ltd,ENERGY,Diversified Energy
3,ADANIGREEN,Adani Green Energy Ltd,POWER,Renewable Energy
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd,PORTS,Ports & Logistics
5,ADANIPOWER,Adani Power Ltd,POWER,Power Generation
6,AMBUJACEM,Ambuja Cements Ltd,CEMENT,Cement
7,APOLLOHOSP,Apollo Hospitals Chain of Indian private hospi...,HEALTHCARE,Hospitals
8,ASIANPAINT,Asian Paints Indian Multi-National Paint and C...,PAINT,Paints
9,ATGL,Adani Total Gas Ltd,ENERGY,Gas Distribution

In [9]:
# Save updated_companies_clean.csv
updated_companies_df.to_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\updated_companies_clean.csv",
    index=False
)

print("updated_companies_clean.csv saved successfully.")

updated_companies_clean.csv saved successfully.

In [10]:
# Create company_sector_intelligence.csv
company_sector_intelligence_df = scores_df.merge(
    updated_companies_df[[
        "symbol",
        "sector",
        "sub_sector"
    ]],
    on="symbol",
    how="left"
)

company_sector_intelligence_df.head()

,symbol,company_name,fiscal_year,net_profit_margin_pct,expense_ratio_pct,debt_to_equity,free_cash_flow,net_profit,profitability_score,expense_score,...,health_score,health_category,dividend_payout,overall_score,leverage_score,dividend_score,growth_score,trend_score,sector,sub_sector
0,ABB,Abbott India Ltd,2024,20.533425,75.158147,0.022438,797.0,1201,25,18,...,93,STRONG,73.0,93,25,20,20,20,PHARMA,Healthcare
1,ADANIENSOL,Adani Energy Solutions Ltd,2024,7.201782,65.610887,2.932521,1095.0,1196,10,18,...,61,WEAK,0.0,61,8,6,8,20,POWER,Power Transmission
2,ADANIENT,Adani Enterprises Ltd,2024,3.458790,88.200703,1.671358,-8455.0,3335,10,10,...,48,WEAK,5.0,48,18,6,8,8,ENERGY,Diversified Energy
3,ADANIGREEN,Adani Green Energy Ltd,2024,13.665944,20.629067,6.595282,-13347.0,1260,18,25,...,61,WEAK,0.0,61,8,6,14,8,POWER,Renewable Energy
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd,2024,30.339560,41.634533,0.937322,8250.0,8104,25,25,...,100,STRONG,16.0,100,25,12,20,20,PORTS,Ports & Logistics

In [11]:
# Cross Check Final Intelligence File
print(company_sector_intelligence_df[["sector", "sub_sector"]].isnull().sum())
print(company_sector_intelligence_df.shape)

company_sector_intelligence_df[[
    "symbol",
    "company_name",
    "sector",
    "sub_sector",
    "overall_score",
    "health_category"
]].head(10)

sector        7
sub_sector    7
dtype: int64
(98, 22)

,symbol,company_name,sector,sub_sector,overall_score,health_category
0,ABB,Abbott India Ltd,PHARMA,Healthcare,93,STRONG
1,ADANIENSOL,Adani Energy Solutions Ltd,POWER,Power Transmission,61,WEAK
2,ADANIENT,Adani Enterprises Ltd,ENERGY,Diversified Energy,48,WEAK
3,ADANIGREEN,Adani Green Energy Ltd,POWER,Renewable Energy,61,WEAK
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd,PORTS,Ports & Logistics,100,STRONG
5,ADANIPOWER,Adani Power Ltd,POWER,Power Generation,93,STRONG
6,AMBUJACEM,Ambuja Cements Ltd,CEMENT,Cement,63,WEAK
7,APOLLOHOSP,Apollo Hospitals Chain of Indian private hospi...,HEALTHCARE,Hospitals,70,MODERATE
8,ASIANPAINT,Asian Paints Indian Multi-National Paint and C...,PAINT,Paints,86,STRONG
9,ATGL,Adani Total Gas Ltd,ENERGY,Gas Distribution,86,STRONG

In [12]:
# Missing Mapping Cross Check
missing_sector_df = company_sector_intelligence_df[
    company_sector_intelligence_df["sector"].isnull()
][["symbol", "company_name"]]

missing_sector_df

        symbol company_name
90  ULTRACEMCO   ULTRACEMCO
91   UNIONBANK    UNIONBANK
92    UNITDSPR     UNITDSPR
93        VEDL         VEDL
94       WIPRO        WIPRO
95      ZOMATO       ZOMATO
96   ZYDUSLIFE    ZYDUSLIFE

In [13]:
# Add Missing Sector Mapping
additional_sector_mapping = pd.DataFrame([
    {"symbol": "ULTRACEMCO", "sector": "CEMENT", "sub_sector": "Cement"},
    {"symbol": "UNIONBANK", "sector": "BANKING", "sub_sector": "Public Bank"},
    {"symbol": "UNITDSPR", "sector": "FMCG", "sub_sector": "Alcoholic Beverages"},
    {"symbol": "VEDL", "sector": "METALS", "sub_sector": "Metals & Mining"},
    {"symbol": "WIPRO", "sector": "IT", "sub_sector": "IT Services"},
    {"symbol": "ZOMATO", "sector": "CONSUMER GOODS", "sub_sector": "Food Delivery"},
    {"symbol": "ZYDUSLIFE", "sector": "PHARMA", "sub_sector": "Pharmaceuticals"}
])

sector_mapping_df = pd.concat(
    [sector_mapping_df, additional_sector_mapping],
    ignore_index=True
).drop_duplicates(subset=["symbol"], keep="last")

print("Updated sector mapping rows:", sector_mapping_df.shape[0])

Updated sector mapping rows: 99

In [14]:
# AGAIN Cross Check Final Intelligence File
company_sector_intelligence_df = scores_df.merge(
    sector_mapping_df,
    on="symbol",
    how="left"
)

print(company_sector_intelligence_df[["sector", "sub_sector"]].isnull().sum())
print(company_sector_intelligence_df.shape)

company_sector_intelligence_df[[
    "symbol",
    "company_name",
    "sector",
    "sub_sector",
    "overall_score",
    "health_category"
]].tail(10)

sector        0
sub_sector    0
dtype: int64
(98, 22)

,symbol,company_name,sector,sub_sector,overall_score,health_category
88,TRENT,Trent Ltd,CONSUMER GOODS,Retail,78,MODERATE
89,TVSMOTOR,TVS Motor Company Ltd,AUTO,Two Wheelers,38,WEAK
90,ULTRACEMCO,ULTRACEMCO,CEMENT,Cement,70,MODERATE
91,UNIONBANK,UNIONBANK,BANKING,Public Bank,76,MODERATE
92,UNITDSPR,UNITDSPR,FMCG,Alcoholic Beverages,78,MODERATE
93,VEDL,VEDL,METALS,Metals & Mining,61,WEAK
94,WIPRO,WIPRO,IT,IT Services,78,MODERATE
95,ZOMATO,ZOMATO,CONSUMER GOODS,Food Delivery,70,MODERATE
96,ZYDUSLIFE,ZYDUSLIFE,PHARMA,Pharmaceuticals,93,STRONG
97,INDIGO,Interglobe Aviation Ltd,AVIATION,Airlines,93,STRONG

In [15]:
# Save Final Files
sector_mapping_df.to_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\sector_mapping.csv",
    index=False
)

company_sector_intelligence_df.to_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\company_sector_intelligence.csv",
    index=False
)

print("sector_mapping.csv saved successfully.")
print("company_sector_intelligence.csv saved successfully.")

sector_mapping.csv saved successfully.
company_sector_intelligence.csv saved successfully.

In [16]:
# Cross-check after save
check_df = pd.read_csv(
    r"C:\Users\LENOVO\Desktop\nifty100_project\data\clean\company_sector_intelligence.csv"
)

print(check_df.shape)
print(check_df[["sector", "sub_sector"]].isnull().sum())

(98, 22)
sector        0
sub_sector    0
dtype: int64

In [18]:
!python "C:\Users\LENOVO\Desktop\nifty100_project\etl\03_load_to_postgres.py"

Starting PostgreSQL Warehouse Loader...
============================================================
Validating clean files...
------------------------------------------------------------
companies_clean.csv -> (92, 14)
updated_companies_clean.csv -> (92, 14)
analysis_clean.csv -> (20, 6)
balancesheet_clean.csv -> (1312, 15)
cashflow_clean.csv -> (1185, 9)
profit_clean.csv -> (1119, 13)
prosandcons_clean.csv -> (26, 6)
sector_mapping.csv -> (99, 3)
company_updated_health_scores.csv -> (98, 20)
fact_ml_scores.csv -> (98, 9)
company_sector_intelligence.csv -> (98, 22)
------------------------------------------------------------
Clean file validation completed.


Loading reference tables...
------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 3317, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 448, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 1272, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\util\langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\impl.py", line 175, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 389, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\util\langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\create.py", line 667, in connect
    return dialect.connect(*cargs_tup, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\default.py", line 630, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\nifty100_project\etl\03_load_to_postgres.py", line 199, in <module>
    run_postgres_loader()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\Desktop\nifty100_project\etl\03_load_to_postgres.py", line 184, in run_postgres_loader
    load_reference_tables()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\Desktop\nifty100_project\etl\03_load_to_postgres.py", line 104, in load_reference_tables
    load_csv_to_table(
    ~~~~~~~~~~~~~~~~~^
        "sector_mapping.csv",
        ^^^^^^^^^^^^^^^^^^^^^
        "sector_mapping",
        ^^^^^^^^^^^^^^^^^
        if_exists="replace"
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\Desktop\nifty100_project\etl\03_load_to_postgres.py", line 86, in load_csv_to_table
    df.to_sql(
    ~~~~~~~~~^
        table_name,
        ^^^^^^^^^^^
    ...<2 lines>...
        index=False
        ^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\pandas\core\generic.py", line 3052, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\pandas\io\sql.py", line 840, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\pandas\io\sql.py", line 908, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\pandas\io\sql.py", line 1649, in __init__
    con = self.exit_stack.enter_context(con.connect())
                                        ~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 3293, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        err, dialect, engine
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 2448, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\base.py", line 3317, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 448, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 1272, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\util\langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\impl.py", line 175, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 389, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\util\langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\create.py", line 667, in connect
    return dialect.connect(*cargs_tup, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\sqlalchemy\engine\default.py", line 630, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [19]:
!python "C:\Users\LENOVO\Desktop\nifty100_project\etl\02_clean_transform.py"

Starting Nifty100 ETL Pipeline...
------------------------------------------------------------
Loaded: companies.xlsx -> (92, 12)
Loaded: balancesheet.xlsx -> (1312, 13)
Loaded: cashflow.xlsx -> (1187, 7)
Loaded: analysis.xlsx -> (20, 6)
Loaded: profitandloss.xlsx -> (1276, 15)
Extraction completed.
------------------------------------------------------------
Transformation completed.
------------------------------------------------------------
Saved: analysis_clean.csv -> (20, 6)
Saved: companies_clean.csv -> (92, 14)
Saved: balancesheet_clean.csv -> (1312, 15)
Saved: cashflow_clean.csv -> (1185, 9)
Saved: prosandcons_clean.csv -> (26, 6)
Saved: profit_clean.csv -> (1119, 13)
------------------------------------------------------------
ETL Pipeline completed successfully.
Sector enrichment pipeline completed successfully.

In [20]:
!python "C:\Users\LENOVO\Desktop\nifty100_project\etl\01_extract_from_mysql.py"

Starting Extraction Pipeline...
------------------------------------------------------------
Loaded: companies.xlsx -> (92, 12)
Loaded: balancesheet.xlsx -> (1312, 13)
Loaded: cashflow.xlsx -> (1187, 7)
Loaded: analysis.xlsx -> (20, 6)
Loaded: profitandloss.xlsx -> (1276, 15)
------------------------------------------------------------
Extraction completed successfully.